name: Build Windows Executable Artifact

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
        shell: bash
      - name: Remove Dev Dependencies
        run: poetry remove -D pytest pytest-mock
      - name: Install Dependencies
        run: poetry install
      - name: Install Pyinstaller
        run: poetry add pyinstaller
      - name: Build Executable
        run: poetry run pyinstaller app.py --name ingredient-extractor
      - name: Build Artifact
        uses: actions/upload-artifact@v2
        with:
           name: ingredient-extractor
           path: dist/*
